name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure required secrets are available
        shell: bash
        run: |
          if [[ -z "${SUPABASE_ACCESS_TOKEN}" ]]; then
            echo "::error::Missing required secret SUPABASE_ACCESS_TOKEN" >&2
            exit 1
          fi
          if [[ -z "${SUPABASE_PROJECT_REF}" ]]; then
            echo "::error::Missing required secret SUPABASE_PROJECT_REF" >&2
            exit 1
          fi

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('supabase/functions/**/deno.lock','supabase/functions/import_map.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Format check
        run: deno fmt --check supabase/functions

      - name: Lint
        run: deno lint supabase/functions

      - name: Test
        run: deno test supabase/functions

      - name: Deploy edge functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: supabase functions deploy hello-world webhook-handler --project-ref "$SUPABASE_PROJECT_REF"
